// SympleX – Polyhedral Tensor Superoptimizer
// Copyright (C) 2025 hollowguy898-cloud
// Licensed under GNU AGPL v3 – see LICENSE file.

#include "symplex/codegen/ptx_emitter.h"
#include <sstream>
#include <algorithm>
#include <cmath>

namespace symplex::codegen {

// ---------------------------------------------------------------------------
// Construction
// ---------------------------------------------------------------------------

PTXEmitter::PTXEmitter(const hardware::HardwareTarget& target)
    : target_(target)
    , wmma_gen_(target)
    , swizzle_gen_(target)
    , reg_alloc_(target)
{}

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

std::string PTXEmitter::ptx_target_arch() const {
    // Map the hardware target to a PTX .target architecture string.
    // We use the SM count and features as a heuristic.
    int64_t num_sms = target_.gpu.num_sms;
    bool has_tma = target_.has_tma;
    bool has_async = target_.has_async_copy;

    if (has_tma && num_sms >= 132) {
        return "sm_90";    // Hopper H100
    }
    if (has_tma && num_sms >= 160) {
        return "sm_100";   // Blackwell B200
    }
    if (has_async && num_sms >= 108) {
        return "sm_80";    // Ampere A100
    }
    if (has_async) {
        return "sm_75";    // Turing
    }
    return "sm_70";        // Volta
}

int64_t PTXEmitter::compute_smem_bytes(
    int64_t tile_m, int64_t tile_n, int64_t tile_k
) const {
    int64_t bpe = target_.bytes_per_element;
    // A tile: tile_m x tile_k elements
    // B tile: tile_k x tile_n elements
    // With double-buffering: 2 stages
    int64_t a_bytes = tile_m * tile_k * bpe;
    int64_t b_bytes = tile_k * tile_n * bpe;
    int64_t stages = target_.pipeline_stages;
    return (a_bytes + b_bytes) * stages;
}

void PTXEmitter::compute_launch_dims(
    int64_t M, int64_t N,
    int64_t tile_m, int64_t tile_n,
    int64_t& grid_x, int64_t& grid_y,
    int64_t& block_x, int64_t& block_y
) const {
    grid_x = (N + tile_n - 1) / tile_n;
    grid_y = (M + tile_m - 1) / tile_m;
    // One warp per CTA tile (conservative); can be scaled up.
    block_x = target_.gpu.warp_size;  // 32 threads per warp
    block_y = 1;
}

// ---------------------------------------------------------------------------
// PTX section builders
// ---------------------------------------------------------------------------

std::string PTXEmitter::emit_ptx_header(const std::string& kernel_name) const {
    std::ostringstream oss;
    oss << "// PTX kernel: " << kernel_name << "\n";
    oss << "// Generated by SympleX Polyhedral Tensor Superoptimizer\n";
    oss << ".version 8.5\n";
    oss << ".target " << ptx_target_arch() << "\n";
    oss << ".address_size 64\n\n";
    return oss.str();
}

std::string PTXEmitter::emit_ptx_param_decls(
    int64_t M, int64_t N, int64_t K
) const {
    std::ostringstream oss;
    oss << "// ---- Kernel parameters ----\n";
    oss << ".param .u64 " << "__param_A_ptr\n";
    oss << ".param .u64 " << "__param_B_ptr\n";
    oss << ".param .u64 " << "__param_C_ptr\n";
    oss << ".param .u64 " << "__param_M\n";
    oss << ".param .u64 " << "__param_N\n";
    oss << ".param .u64 " << "__param_K\n";
    oss << "\n";
    return oss.str();
}

std::string PTXEmitter::emit_ptx_shared_mem_decl(
    int64_t tile_m, int64_t tile_n, int64_t tile_k
) const {
    std::ostringstream oss;
    int64_t bpe = target_.bytes_per_element;
    int64_t stages = target_.pipeline_stages;

    // Shared memory for A tiles (pipeline_stages * tile_m * tile_k * bpe)
    int64_t smem_a_bytes = stages * tile_m * tile_k * bpe;
    // Shared memory for B tiles (pipeline_stages * tile_k * tile_n * bpe)
    int64_t smem_b_bytes = stages * tile_k * tile_n * bpe;

    oss << "// ---- Shared memory ----\n";
    oss << ".shared .align " << target_.memory_alignment << " .b8 smem_A["
        << smem_a_bytes << "];\n";
    oss << ".shared .align " << target_.memory_alignment << " .b8 smem_B["
        << smem_b_bytes << "];\n";
    oss << "\n";
    return oss.str();
}

std::string PTXEmitter::emit_ptx_prologue() const {
    std::ostringstream oss;

    oss << "    // ---- Prologue ----\n";
    oss << "    // Load kernel parameters\n";
    oss << "    ld.param.u64 %rd_a_ptr, [__param_A_ptr];\n";
    oss << "    ld.param.u64 %rd_b_ptr, [__param_B_ptr];\n";
    oss << "    ld.param.u64 %rd_c_ptr, [__param_C_ptr];\n";
    oss << "    ld.param.u64 %rd_M,     [__param_M];\n";
    oss << "    ld.param.u64 %rd_N,     [__param_N];\n";
    oss << "    ld.param.u64 %rd_K,     [__param_K];\n";
    oss << "\n";

    oss << "    // Compute CTA (block) and thread indices\n";
    oss << "    mov.u64 %rd_ctaid_x, %ctaid.x;\n";
    oss << "    mov.u64 %rd_ctaid_y, %ctaid.y;\n";
    oss << "    mov.u64 %rd_tid_x,   %tid.x;\n";
    oss << "    mov.u64 %rd_warp_id, %tid.x;\n";
    oss << "    shr.u64 %rd_warp_id, %rd_warp_id, 5;  // warp_id = tid / 32\n";
    oss << "    and.b64  %rd_lane_id, %rd_tid_x, 31;  // lane_id = tid % 32\n";
    oss << "\n";

    // Compute global row/col offsets for this CTA
    oss << "    // Global row offset = blockIdx.y * tile_m\n";
    oss << "    // Global col offset = blockIdx.x * tile_n\n";
    oss << "    // (tile dimensions are folded into the loop below)\n";
    oss << "\n";

    // Shared memory base pointers
    oss << "    // Shared memory base addresses\n";
    oss << "    mov.u64 %rd_smem_A, smem_A;\n";
    oss << "    mov.u64 %rd_smem_B, smem_B;\n";
    oss << "\n";

    return oss.str();
}

std::string PTXEmitter::emit_ptx_tiling_loop(
    int64_t M, int64_t N, int64_t K,
    const schedule::TileConfig& tile
) const {
    std::ostringstream oss;

    // Extract tile dimensions
    int64_t tile_m = (tile.inner_tiles.size() > 0) ? tile.inner_tiles[0] : 128;
    int64_t tile_n = (tile.inner_tiles.size() > 1) ? tile.inner_tiles[1] : 128;
    int64_t tile_k = (tile.inner_tiles.size() > 2) ? tile.inner_tiles[2] : 32;

    int64_t stages = target_.pipeline_stages;
    int64_t bpe = target_.bytes_per_element;
    int64_t smem_a_stride = tile_k;  // A is M x K, row-major, stride=K
    int64_t smem_b_stride = tile_n;  // B is K x N, row-major, stride=N

    // Grid dimensions
    int64_t grid_x, grid_y, block_x, block_y;
    compute_launch_dims(M, N, tile_m, tile_n, grid_x, grid_y, block_x, block_y);

    oss << "    // ---- Tiling loop ----\n";
    oss << "    // Tile: " << tile_m << "x" << tile_n << "x" << tile_k << "\n";
    oss << "    // Pipeline stages: " << stages << "\n";
    oss << "    // Grid: " << grid_x << " x " << grid_y << "\n";
    oss << "    // Block: " << block_x << " x " << block_y << "\n";
    oss << "\n";

    // Compute global offsets for this CTA
    oss << "    // Compute base global pointers for this CTA\n";
    oss << "    // CTA row base = blockIdx.y * " << tile_m << "\n";
    oss << "    // CTA col base = blockIdx.x * " << tile_n << "\n";
    oss << "    mul.lo.u64 %rd_row_base, %rd_ctaid_y, " << tile_m << ";\n";
    oss << "    mul.lo.u64 %rd_col_base, %rd_ctaid_x, " << tile_n << ";\n";
    oss << "\n";

    // Initialise C accumulator to zero
    const auto& wcfg = wmma_gen_.config();
    int64_t rep_m = tile_m / wcfg.m;
    int64_t rep_n = tile_n / wcfg.n;

    oss << "    // Zero C accumulator registers\n";
    for (int64_t rm = 0; rm < rep_m; ++rm) {
        for (int64_t rn = 0; rn < rep_n; ++rn) {
            for (int i = 0; i < 4; ++i) {
                oss << "    mov.f32 %R_c" << rm << "_" << rn << "_" << i
                    << ", 0.0;\n";
            }
        }
    }
    oss << "\n";

    // K-loop
    int64_t k_iters = (K + tile_k - 1) / tile_k;
    oss << "    // K-loop: " << k_iters << " iterations\n";
    oss << "    mov.u64 %rd_k_iter, 0;\n";
    oss << "    mov.u64 %rd_k_offset, 0;\n";
    oss << "\n";

    oss << "K_LOOP:\n";

    // ── Async copy from global to shared memory ──
    if (target_.has_tma) {
        oss << "    // TMA copy: A tile from global to shared memory\n";
        oss << "    // cp.async.bulk.tensor.2d.shared.global.mbarrier::complete_tx::bytes\n";
        oss << "    //   smem_A[stage], [A_tensor_desc, row_base, k_offset], tile_m*"
            << tile_k << "*" << bpe << " bytes, barrier\n";
        oss << "    {\n";
        oss << "        .reg .u64 %tma_bytes_a;\n";
        oss << "        mov.u64 %tma_bytes_a, " << (tile_m * tile_k * bpe) << ";\n";
        oss << "        cp.async.bulk.tensor.2d.shared.global"
            << ".mbarrier::complete_tx::bytes"
            << " [%rd_smem_A_stage], [%rd_a_tma_desc, %rd_row_base, %rd_k_offset],"
            << " %tma_bytes_a, [%rd_barrier];\n";
        oss << "    }\n";
        oss << "\n";

        oss << "    // TMA copy: B tile from global to shared memory\n";
        oss << "    {\n";
        oss << "        .reg .u64 %tma_bytes_b;\n";
        oss << "        mov.u64 %tma_bytes_b, " << (tile_k * tile_n * bpe) << ";\n";
        oss << "        cp.async.bulk.tensor.2d.shared.global"
            << ".mbarrier::complete_tx::bytes"
            << " [%rd_smem_B_stage], [%rd_b_tma_desc, %rd_k_offset, %rd_col_base],"
            << " %tma_bytes_b, [%rd_barrier];\n";
        oss << "    }\n";
        oss << "\n";

        oss << "    // Wait for TMA copies to complete\n";
        oss << "    barrier.wait %rd_barrier;\n";
        oss << "\n";
    } else if (target_.has_async_copy) {
        // cp.async path (Ampere/Turing)
        oss << "    // Async copy A tile from global to shared (cp.async)\n";
        oss << "    // Each warp thread copies a strided subset of elements\n";
        oss << "    {\n";
        oss << "        .reg .u64 %src_a, %dst_a;\n";
        oss << "        .reg .u64 %cp_row, %cp_col;\n";
        oss << "        // Compute per-thread source/dest offsets\n";
        oss << "        mov.u64 %cp_row, %rd_lane_id;\n";
        oss << "        // src = A_ptr + (row_base + cp_row) * K + k_offset\n";
        oss << "        mad.lo.u64 %src_a, %cp_row, %rd_K, %rd_k_offset;\n";
        oss << "        mad.lo.u64 %src_a, %src_a, " << bpe << ", %rd_a_ptr;\n";
        oss << "        // dst = smem_A + cp_row * tile_k * bpe\n";
        oss << "        mad.lo.u64 %dst_a, %cp_row, " << (tile_k * bpe) << ", %rd_smem_A;\n";
        oss << "        cp.async.ca.shared.global [%dst_a], [%src_a], "
            << (tile_k * bpe) << ";\n";
        oss << "    }\n";
        oss << "\n";

        oss << "    // Async copy B tile from global to shared (cp.async)\n";
        oss << "    {\n";
        oss << "        .reg .u64 %src_b, %dst_b;\n";
        oss << "        .reg .u64 %cp_k_row, %cp_n_col;\n";
        oss << "        mov.u64 %cp_k_row, %rd_lane_id;\n";
        oss << "        mad.lo.u64 %src_b, %cp_k_row, %rd_N, %rd_col_base;\n";
        oss << "        mad.lo.u64 %src_b, %src_b, " << bpe << ", %rd_b_ptr;\n";
        oss << "        mad.lo.u64 %dst_b, %cp_k_row, " << (tile_n * bpe)
            << ", %rd_smem_B;\n";
        oss << "        cp.async.ca.shared.global [%dst_b], [%src_b], "
            << (tile_n * bpe) << ";\n";
        oss << "    }\n";
        oss << "\n";

        oss << "    // Commit and wait for async copies\n";
        oss << "    cp.async.commit_group;\n";
        oss << "    cp.async.wait_group 0;\n";
        oss << "\n";
    } else {
        // Synchronous copy (Volta and older)
        oss << "    // Synchronous load A tile to shared memory\n";
        oss << "    // Each thread loads one element at a time\n";
        oss << "    {\n";
        oss << "        .reg .u64 %ld_offset_a;\n";
        oss << "        .reg ." << (bpe == 2 ? "f16" : "f32") << " %ld_val_a;\n";
        oss << "        mov.u64 %ld_offset_a, %rd_lane_id;\n";
        oss << "        // For each row assigned to this thread\n";
        oss << "        ld.global." << (bpe == 2 ? "f16" : "f32")
            << " %ld_val_a, [%rd_a_ptr + %ld_offset_a];\n";
        oss << "        st.shared." << (bpe == 2 ? "f16" : "f32")
            << " [%rd_smem_A + %ld_offset_a], %ld_val_a;\n";
        oss << "    }\n";
        oss << "\n";

        oss << "    // Synchronous load B tile to shared memory\n";
        oss << "    {\n";
        oss << "        .reg .u64 %ld_offset_b;\n";
        oss << "        .reg ." << (bpe == 2 ? "f16" : "f32") << " %ld_val_b;\n";
        oss << "        mov.u64 %ld_offset_b, %rd_lane_id;\n";
        oss << "        ld.global." << (bpe == 2 ? "f16" : "f32")
            << " %ld_val_b, [%rd_b_ptr + %ld_offset_b];\n";
        oss << "        st.shared." << (bpe == 2 ? "f16" : "f32")
            << " [%rd_smem_B + %ld_offset_b], %ld_val_b;\n";
        oss << "    }\n";
        oss << "\n";

        oss << "    bar.sync 0;\n";
        oss << "\n";
    }

    // ── Swizzle before WMMA load ──
    oss << swizzle_gen_.emit_smem_unswizzle(tile_m, tile_k, smem_a_stride);
    oss << "\n";

    // ── WMMA load A from shared memory ──
    oss << wmma_gen_.emit_wmma_load_a(tile_m, tile_k, "%rd_smem_A", smem_a_stride);
    oss << "\n";

    // ── WMMA load B from shared memory ──
    oss << swizzle_gen_.emit_smem_unswizzle(tile_k, tile_n, smem_b_stride);
    oss << "\n";
    oss << wmma_gen_.emit_wmma_load_b(tile_k, tile_n, "%rd_smem_B", smem_b_stride);
    oss << "\n";

    // ── WMMA compute ──
    oss << wmma_gen_.emit_wmma_mma(tile_m, tile_n, tile_k);
    oss << "\n";

    // ── Advance K offset ──
    oss << "    // Advance K offset\n";
    oss << "    add.u64 %rd_k_offset, %rd_k_offset, " << tile_k << ";\n";
    oss << "    add.u64 %rd_k_iter, %rd_k_iter, 1;\n";

    // ── Double-buffer swap ──
    if (stages >= 2) {
        oss << "    // Double-buffer: swap shared memory stage pointers\n";
        oss << "    // stage ^= 1\n";
        oss << "    xor.b64 %rd_stage, %rd_stage, 1;\n";
        oss << "    mov.u64 %rd_smem_A_stage, %rd_smem_A;\n";
        oss << "    mov.u64 %rd_smem_B_stage, %rd_smem_B;\n";
        oss << "    mad.lo.u64 %rd_smem_A_stage, %rd_stage, "
            << (tile_m * tile_k * bpe) << ", %rd_smem_A;\n";
        oss << "    mad.lo.u64 %rd_smem_B_stage, %rd_stage, "
            << (tile_k * tile_n * bpe) << ", %rd_smem_B;\n";
    }

    oss << "\n";

    // ── Loop condition ──
    oss << "    // Loop condition: k_iter < " << k_iters << "\n";
    oss << "    setp.lt.u64 %p_k_loop, %rd_k_iter, " << k_iters << ";\n";
    oss << "    @%p_k_loop bra K_LOOP;\n";
    oss << "\n";

    // ── Barrier after K-loop ──
    oss << "    bar.sync 0;\n";
    oss << "\n";

    return oss.str();
}

std::string PTXEmitter::emit_ptx_epilogue() const {
    std::ostringstream oss;
    oss << "    // ---- Epilogue ----\n";
    oss << "    // Store C accumulator to global memory\n";
    oss << "    // (WMMA store is emitted inline by the tiling loop)\n";
    oss << "\n";

    // Apply swizzle on the way out (if needed for shared memory write-back)
    oss << swizzle_gen_.emit_smem_swizzle(1, 1, 1);
    oss << "\n";

    oss << "    // Compute global C pointer for this CTA\n";
    oss << "    // C_ptr += row_base * N + col_base\n";
    oss << "    mad.lo.u64 %rd_c_gmem, %rd_row_base, %rd_N, %rd_col_base;\n";
    oss << "    mad.lo.u64 %rd_c_gmem, %rd_c_gmem, " << target_.bytes_per_element
        << ", %rd_c_ptr;\n";
    oss << "\n";

    oss << "    // Boundary check: skip store if out of bounds\n";
    oss << "    setp.lt.u64 %p_m_bound, %rd_row_base, %rd_M;\n";
    oss << "    setp.lt.u64 %p_n_bound, %rd_col_base, %rd_N;\n";
    oss << "    and.pred  %p_in_bounds, %p_m_bound, %p_n_bound;\n";
    oss << "    @!%p_in_bounds bra EPILOGUE_SKIP;\n";
    oss << "\n";

    oss << "EPILOGUE_SKIP:\n";
    oss << "    // Kernel exit\n";
    oss << "    ret;\n";
    oss << "\n";
    return oss.str();
}

// ---------------------------------------------------------------------------
// Complete matmul kernel
// ---------------------------------------------------------------------------

std::string PTXEmitter::emit_matmul_kernel(
    int64_t M, int64_t N, int64_t K,
    const schedule::TileConfig& tile,
    const std::string& kernel_name
) const {
    std::ostringstream oss;

    int64_t tile_m = (tile.inner_tiles.size() > 0) ? tile.inner_tiles[0] : 128;
    int64_t tile_n = (tile.inner_tiles.size() > 1) ? tile.inner_tiles[1] : 128;
    int64_t tile_k = (tile.inner_tiles.size() > 2) ? tile.inner_tiles[2] : 32;

    // Header
    oss << emit_ptx_header(kernel_name);

    // Entry point declaration
    int64_t grid_x, grid_y, block_x, block_y;
    compute_launch_dims(M, N, tile_m, tile_n, grid_x, grid_y, block_x, block_y);

    oss << ".entry " << kernel_name << "(\n";
    oss << "    .param .u64 A_ptr,\n";
    oss << "    .param .u64 B_ptr,\n";
    oss << "    .param .u64 C_ptr,\n";
    oss << "    .param .u64 dim_M,\n";
    oss << "    .param .u64 dim_N,\n";
    oss << "    .param .u64 dim_K\n";
    oss << ")\n{\n";

    // Shared memory
    oss << emit_ptx_shared_mem_decl(tile_m, tile_n, tile_k);

    // Register declarations
    oss << "    // ---- Register declarations ----\n";
    oss << "    .reg .u64 %rd_ctaid_x, %rd_ctaid_y;\n";
    oss << "    .reg .u64 %rd_tid_x;\n";
    oss << "    .reg .u64 %rd_warp_id, %rd_lane_id;\n";
    oss << "    .reg .u64 %rd_a_ptr, %rd_b_ptr, %rd_c_ptr;\n";
    oss << "    .reg .u64 %rd_M, %rd_N, %rd_K;\n";
    oss << "    .reg .u64 %rd_row_base, %rd_col_base;\n";
    oss << "    .reg .u64 %rd_k_iter, %rd_k_offset;\n";
    oss << "    .reg .u64 %rd_smem_A, %rd_smem_B;\n";
    oss << "    .reg .u64 %rd_smem_A_stage, %rd_smem_B_stage;\n";
    oss << "    .reg .u64 %rd_stage;\n";
    oss << "    .reg .u64 %rd_c_gmem;\n";

    if (target_.has_tma) {
        oss << "    .reg .u64 %rd_a_tma_desc, %rd_b_tma_desc;\n";
        oss << "    .reg .u64 %rd_barrier;\n";
    }

    oss << "    .reg .pred %p_k_loop, %p_m_bound, %p_n_bound, %p_in_bounds;\n";

    // C accumulator registers
    int64_t rep_m = tile_m / wmma_gen_.config().m;
    int64_t rep_n = tile_n / wmma_gen_.config().n;
    for (int64_t rm = 0; rm < rep_m; ++rm) {
        for (int64_t rn = 0; rn < rep_n; ++rn) {
            for (int i = 0; i < 4; ++i) {
                oss << "    .reg .f32 %R_c" << rm << "_" << rn << "_" << i << ";\n";
            }
        }
    }
    oss << "\n";

    // Prologue
    oss << emit_ptx_prologue();

    // WMMA store C (in epilogue)
    oss << wmma_gen_.emit_wmma_store_c(tile_m, tile_n, "%rd_c_gmem", N);

    // Tiling loop
    oss << emit_ptx_tiling_loop(M, N, K, tile);

    // Epilogue
    oss << emit_ptx_epilogue();

    oss << "}\n";
    return oss.str();
}

// ---------------------------------------------------------------------------
// Conv2d helpers
// ---------------------------------------------------------------------------

std::string PTXEmitter::emit_conv2d_param_decls(
    int64_t batch, int64_t oc, int64_t ic,
    int64_t oh, int64_t ow, int64_t kh, int64_t kw,
    int64_t stride, int64_t pad
) const {
    std::ostringstream oss;
    oss << "    .param .u64 input_ptr,\n";
    oss << "    .param .u64 kernel_ptr,\n";
    oss << "    .param .u64 output_ptr,\n";
    oss << "    .param .u64 dim_batch,\n";
    oss << "    .param .u64 dim_oc,\n";
    oss << "    .param .u64 dim_ic,\n";
    oss << "    .param .u64 dim_oh,\n";
    oss << "    .param .u64 dim_ow,\n";
    oss << "    .param .u64 dim_kh,\n";
    oss << "    .param .u64 dim_kw,\n";
    oss << "    .param .u64 dim_stride,\n";
    oss << "    .param .u64 dim_pad\n";
    return oss.str();
}

std::string PTXEmitter::emit_conv2d_tiling_loop(
    int64_t batch, int64_t oc, int64_t ic,
    int64_t oh, int64_t ow, int64_t kh, int64_t kw,
    int64_t stride, int64_t pad,
    const schedule::TileConfig& tile
) const {
    std::ostringstream oss;
    int64_t bpe = target_.bytes_per_element;

    // Conv2d is lowered to an im2col GEMM:
    //   output[batch*oc*oh*ow] = im2col(input) * kernel[oc*ic*kh*kw]
    // The im2col matrix has dimensions (batch*oh*ow) x (ic*kh*kw)
    // The kernel matrix has dimensions (ic*kh*kw) x oc
    // So the effective GEMM is:
    //   M = batch * oh * ow
    //   N = oc
    //   K = ic * kh * kw

    int64_t eff_M = batch * oh * ow;
    int64_t eff_N = oc;
    int64_t eff_K = ic * kh * kw;

    int64_t tile_m = (tile.inner_tiles.size() > 0) ? tile.inner_tiles[0] : 128;
    int64_t tile_n = (tile.inner_tiles.size() > 1) ? tile.inner_tiles[1] : 128;
    int64_t tile_k = (tile.inner_tiles.size() > 2) ? tile.inner_tiles[2] : 32;

    // Align tile_k to kh*kw for clean im2col rows
    int64_t kw_kh = kh * kw;
    if (kw_kh > 0 && tile_k % kw_kh != 0) {
        tile_k = ((tile_k + kw_kh - 1) / kw_kh) * kw_kh;
    }

    oss << "    // Conv2d lowered to im2col GEMM:\n";
    oss << "    //   M = batch*oh*ow = " << eff_M << "\n";
    oss << "    //   N = oc = " << eff_N << "\n";
    oss << "    //   K = ic*kh*kw = " << eff_K << "\n";
    oss << "    // Tile: " << tile_m << "x" << tile_n << "x" << tile_k << "\n";
    oss << "\n";

    // K-loop for the im2col GEMM
    int64_t k_iters = (eff_K + tile_k - 1) / tile_k;
    oss << "    mov.u64 %rd_k_iter, 0;\n";
    oss << "    mov.u64 %rd_k_offset, 0;\n";
    oss << "\n";

    oss << "CONV2D_K_LOOP:\n";

    // For conv2d, the A "matrix" is the im2col expansion of the input tensor.
    // Each row (batch_idx, oh_idx, ow_idx) generates ic*kh*kw elements by
    // gathering from input[batch, ic, oh*s+kh-pad, ow*s+kw-pad].
    // We emit the gather pattern inline.

    oss << "    // ---- Im2col gather: load input tile to shared memory ----\n";
    oss << "    // For each output pixel in the tile, gather from input\n";
    oss << "    // using stride=" << stride << ", pad=" << pad << "\n";
    oss << "    {\n";
    oss << "        .reg .u64 %im_row, %im_col, %im_batch;\n";
    oss << "        .reg .u64 %im_ih, %im_iw;\n";
    oss << "        .reg .u64 %im_ic, %im_kh, %im_kw;\n";
    oss << "        .reg .u64 %im_src_offset;\n";
    oss << "        .reg ." << (bpe == 2 ? "f16" : "f32") << " %im_val;\n";
    oss << "        .reg .pred %im_pad_pred;\n";
    oss << "\n";

    oss << "        // Thread %lane_id gathers one element\n";
    oss << "        // Decompose linear index into (batch, oh, ow, ic, kh, kw)\n";
    oss << "        // using the k_offset to determine the ic/kh/kw coordinates\n";
    oss << "        mov.u64 %im_kh, %rd_k_offset;\n";
    oss << "        div.u64 %im_ic, %im_kh, " << kw_kh << ";\n";
    oss << "        rem.u64 %im_kh, %im_kh, " << kw_kh << ";\n";
    oss << "        div.u64 %im_kw, %im_kh, " << kw << ";\n";
    oss << "        rem.u64 %im_kw, %im_kh, " << kw << ";\n";
    oss << "        // Actually im_kh is now the remainder, re-derive:\n";
    oss << "        mov.u64 %im_kh_row, %im_kh;\n";
    oss << "        div.u64 %im_kh, %im_kh_row, " << kw << ";\n";
    oss << "        rem.u64 %im_kw, %im_kh_row, " << kw << ";\n";
    oss << "\n";

    oss << "        // Compute input spatial coordinates\n";
    oss << "        // ih = oh * stride + kh - pad\n";
    oss << "        // iw = ow * stride + kw - pad\n";
    oss << "        mad.lo.u64 %im_ih, %rd_oh, " << stride << ", %im_kh;\n";
    oss << "        sub.u64 %im_ih, %im_ih, " << pad << ";\n";
    oss << "        mad.lo.u64 %im_iw, %rd_ow, " << stride << ", %im_kw;\n";
    oss << "        sub.u64 %im_iw, %im_iw, " << pad << ";\n";
    oss << "\n";

    oss << "        // Check if within input bounds (not padding)\n";
    oss << "        setp.ge.u64 %im_pad_pred, %im_ih, 0;\n";
    oss << "        setp.lt.u64 %im_pad_pred, %im_ih, " << (oh * stride + kh) << ";\n";
    oss << "        // Load if not in padding region\n";
    oss << "        @%im_pad_pred ld.global." << (bpe == 2 ? "f16" : "f32")
        << " %im_val, [%rd_input_ptr + %im_src_offset];\n";
    oss << "        @!%im_pad_pred mov." << (bpe == 2 ? "f16" : "f32")
        << " %im_val, 0;\n";
    oss << "        st.shared." << (bpe == 2 ? "f16" : "f32")
        << " [%rd_smem_A + %rd_lane_id], %im_val;\n";
    oss << "    }\n";
    oss << "\n";

    // Load kernel tile (similar to B in GEMM)
    oss << "    // Load kernel tile to shared memory\n";
    oss << "    // Kernel is stored as [oc, ic, kh, kw], so the B tile\n";
    oss << "    // for this K slice starts at kernel_ptr + k_offset * oc\n";
    if (target_.has_async_copy) {
        oss << "    cp.async.ca.shared.global [%rd_smem_B], [%rd_kernel_ptr + %rd_k_offset_b], "
            << (tile_n * tile_k * bpe / target_.gpu.warp_size) << ";\n";
        oss << "    cp.async.commit_group;\n";
        oss << "    cp.async.wait_group 0;\n";
    } else {
        oss << "    ld.global." << (bpe == 2 ? "f16" : "f32")
            << " %conv_b_val, [%rd_kernel_ptr + %rd_lane_id];\n";
        oss << "    st.shared." << (bpe == 2 ? "f16" : "f32")
            << " [%rd_smem_B + %rd_lane_id], %conv_b_val;\n";
    }
    oss << "\n";

    oss << "    bar.sync 0;\n";
    oss << "\n";

    // WMMA on the gathered tiles
    oss << wmma_gen_.emit_wmma_load_a(tile_m, tile_k, "%rd_smem_A", tile_k);
    oss << wmma_gen_.emit_wmma_load_b(tile_k, tile_n, "%rd_smem_B", tile_n);
    oss << wmma_gen_.emit_wmma_mma(tile_m, tile_n, tile_k);
    oss << "\n";

    // Advance K
    oss << "    add.u64 %rd_k_offset, %rd_k_offset, " << tile_k << ";\n";
    oss << "    add.u64 %rd_k_iter, %rd_k_iter, 1;\n";
    oss << "    setp.lt.u64 %p_k_loop, %rd_k_iter, " << k_iters << ";\n";
    oss << "    @%p_k_loop bra CONV2D_K_LOOP;\n";
    oss << "\n";

    return oss.str();
}

// ---------------------------------------------------------------------------
// Complete conv2d kernel
// ---------------------------------------------------------------------------

std::string PTXEmitter::emit_conv2d_kernel(
    int64_t batch, int64_t oc, int64_t ic,
    int64_t oh, int64_t ow, int64_t kh, int64_t kw,
    int64_t stride, int64_t pad,
    const schedule::TileConfig& tile,
    const std::string& kernel_name
) const {
    std::ostringstream oss;

    int64_t tile_m = (tile.inner_tiles.size() > 0) ? tile.inner_tiles[0] : 128;
    int64_t tile_n = (tile.inner_tiles.size() > 1) ? tile.inner_tiles[1] : 128;
    int64_t tile_k = (tile.inner_tiles.size() > 2) ? tile.inner_tiles[2] : 32;
    int64_t bpe = target_.bytes_per_element;

    // Header
    oss << emit_ptx_header(kernel_name);

    // Entry point
    oss << ".entry " << kernel_name << "(\n";
    oss << emit_conv2d_param_decls(batch, oc, ic, oh, ow, kh, kw, stride, pad);
    oss << ")\n{\n";

    // Shared memory
    oss << emit_ptx_shared_mem_decl(tile_m, tile_n, tile_k);

    // Register declarations
    oss << "    // ---- Register declarations ----\n";
    oss << "    .reg .u64 %rd_ctaid_x, %rd_ctaid_y, %rd_ctaid_z;\n";
    oss << "    .reg .u64 %rd_tid_x;\n";
    oss << "    .reg .u64 %rd_warp_id, %rd_lane_id;\n";
    oss << "    .reg .u64 %rd_input_ptr, %rd_kernel_ptr, %rd_output_ptr;\n";
    oss << "    .reg .u64 %rd_batch, %rd_oc, %rd_ic;\n";
    oss << "    .reg .u64 %rd_oh, %rd_ow, %rd_kh, %rd_kw;\n";
    oss << "    .reg .u64 %rd_stride, %rd_pad;\n";
    oss << "    .reg .u64 %rd_row_base, %rd_col_base;\n";
    oss << "    .reg .u64 %rd_k_iter, %rd_k_offset;\n";
    oss << "    .reg .u64 %rd_smem_A, %rd_smem_B;\n";
    oss << "    .reg .u64 %rd_out_gmem;\n";
    oss << "    .reg .pred %p_k_loop, %p_in_bounds;\n";
    oss << "    .reg ." << (bpe == 2 ? "f16" : "f32") << " %conv_b_val;\n";

    // C accumulator registers
    int64_t rep_m = tile_m / wmma_gen_.config().m;
    int64_t rep_n = tile_n / wmma_gen_.config().n;
    for (int64_t rm = 0; rm < rep_m; ++rm) {
        for (int64_t rn = 0; rn < rep_n; ++rn) {
            for (int i = 0; i < 4; ++i) {
                oss << "    .reg .f32 %R_c" << rm << "_" << rn << "_" << i << ";\n";
            }
        }
    }
    oss << "\n";

    // Prologue: load parameters
    oss << "    // ---- Conv2d Prologue ----\n";
    oss << "    ld.param.u64 %rd_input_ptr,  [input_ptr];\n";
    oss << "    ld.param.u64 %rd_kernel_ptr, [kernel_ptr];\n";
    oss << "    ld.param.u64 %rd_output_ptr, [output_ptr];\n";
    oss << "    ld.param.u64 %rd_batch, [dim_batch];\n";
    oss << "    ld.param.u64 %rd_oc,     [dim_oc];\n";
    oss << "    ld.param.u64 %rd_ic,     [dim_ic];\n";
    oss << "    ld.param.u64 %rd_oh,     [dim_oh];\n";
    oss << "    ld.param.u64 %rd_ow,     [dim_ow];\n";
    oss << "    ld.param.u64 %rd_kh,     [dim_kh];\n";
    oss << "    ld.param.u64 %rd_kw,     [dim_kw];\n";
    oss << "    ld.param.u64 %rd_stride, [dim_stride];\n";
    oss << "    ld.param.u64 %rd_pad,    [dim_pad];\n";
    oss << "\n";

    oss << "    // Compute CTA indices\n";
    oss << "    mov.u64 %rd_ctaid_x, %ctaid.x;\n";
    oss << "    mov.u64 %rd_ctaid_y, %ctaid.y;\n";
    oss << "    mov.u64 %rd_ctaid_z, %ctaid.z;\n";
    oss << "    mov.u64 %rd_tid_x,   %tid.x;\n";
    oss << "    mov.u64 %rd_warp_id, %rd_tid_x;\n";
    oss << "    shr.u64 %rd_warp_id, %rd_warp_id, 5;\n";
    oss << "    and.b64 %rd_lane_id, %rd_tid_x, 31;\n";
    oss << "\n";

    // Shared memory base pointers
    oss << "    mov.u64 %rd_smem_A, smem_A;\n";
    oss << "    mov.u64 %rd_smem_B, smem_B;\n";
    oss << "\n";

    // Zero C accumulators
    oss << "    // Zero C accumulators\n";
    for (int64_t rm = 0; rm < rep_m; ++rm) {
        for (int64_t rn = 0; rn < rep_n; ++rn) {
            for (int i = 0; i < 4; ++i) {
                oss << "    mov.f32 %R_c" << rm << "_" << rn << "_" << i
                    << ", 0.0;\n";
            }
        }
    }
    oss << "\n";

    // Conv2d tiling loop (im2col GEMM)
    oss << emit_conv2d_tiling_loop(
        batch, oc, ic, oh, ow, kh, kw, stride, pad, tile);

    // Store output
    oss << "    // Store output to global memory\n";
    oss << wmma_gen_.emit_wmma_store_c(tile_m, tile_n, "%rd_output_ptr", oc * oh * ow);

    // Epilogue
    oss << "    bar.sync 0;\n";
    oss << "    ret;\n";
    oss << "}\n";

    return oss.str();
}

} // namespace symplex::codegen
